on:
  push:
    tags:
    - 'v*' # tags that look like release numbers, eg v1.0.0

name: Create Binary Release

jobs:
  build:
    name: Create Binary Release
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.09.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Restore opam cache
        uses: actions/cache@v2
        with:
          path: ${HOME}/.opam
          key: ${{ runner.os }}-${{ hashFiles('opam.locked') }}

      - name: Install Required Ubuntu Packages
        run: |
          sudo apt-get install --yes --no-install-recommends \
            autoconf \
            debianutils \
            libgmp-dev \
            libmpfr-dev \
            libsqlite3-dev \
            m4 \
            opam \
            perl \
            pkg-config \
            zlib1g-dev
        if: runner.os == 'Linux'

      - name: Install Required Brew Packages for MacOS
        run: |
          brew install autoconf automake cmake opam pkg-config sqlite gmp mpfr
          brew cask install java
        if: runner.os == 'macOS'

      - name: Build release tarball for version ${{ github.ref }}
        id: build_release_tarball
        run:
          ./scripts/create_binary_release.sh "$(echo ${{ github.ref }} | rev | cut -d / -f 1 | rev)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.build_release_tarball.outputs.release_tarball}}
          asset_name: ${{ steps.build_release_tarball.outputs.release_tarball}}
